
package org.hl7.ctsvapi;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "BrowserOperationsService", targetNamespace = "urn://hl7.org/CTSVAPI", wsdlLocation = "http://localhost:8080/axis/services/VocabBrowserService/#%7Burn%3A%2F%2Fhl7.org%2FCTSVAPI%7DBrowserOperationsService?wsdl")
public class BrowserOperationsService extends Service {

    /**
     * WSDL.
     */
    private final static URL BROWSEROPERATIONSSERVICE_WSDL_LOCATION;
    
    /**
     * Logger.
     */
    private final static Logger logger = Logger.getLogger(BrowserOperationsService.class.getName());

    static {
        URL url = null;
        try {
//            URL baseUrl;
//            baseUrl = org.hl7.ctsvapi.BrowserOperationsService.class.getResource(".");
            url = new URL("http://localhost:8080/axis/services/VocabBrowserService/#%7Burn%3A%2F%2Fhl7.org%2FCTSVAPI%7DBrowserOperationsService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/axis/services/VocabBrowserService/#%7Burn%3A%2F%2Fhl7.org%2FCTSVAPI%7DBrowserOperationsService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BROWSEROPERATIONSSERVICE_WSDL_LOCATION = url;
    }

    /**
     * Constructor.
     * 
     * @param wsdlLocation WSDL
     * @param serviceName service
     */
    public BrowserOperationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Constructor.
     */
    public BrowserOperationsService() {
        super(BROWSEROPERATIONSSERVICE_WSDL_LOCATION, new QName("urn://hl7.org/CTSVAPI", "BrowserOperationsService"));
    }

    /**
     * 
     * @return
     *     returns BrowserOperations
     */
    @WebEndpoint(name = "VocabBrowserService")
    public BrowserOperations getVocabBrowserService() {
        return super.getPort(new QName("urn://hl7.org/CTSVAPI", "VocabBrowserService"), BrowserOperations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BrowserOperations
     */
    @WebEndpoint(name = "VocabBrowserService")
    public BrowserOperations getVocabBrowserService(WebServiceFeature... features) {
        return super.getPort(new QName("urn://hl7.org/CTSVAPI", "VocabBrowserService"), BrowserOperations.class, features);
    }

}
