
package org.hl7.ctsvapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault1", targetNamespace = "urn://hl7.org/CTSVAPI")
public class InvalidExpansionContext_Exception extends Exception {

    /**
     * Class UID.
     */
    private static final long serialVersionUID = -646193740209013880L;
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidExpansionContext faultInfo;

    /**
     * 
     * @param message message
     * @param faultInfo fault
     */
    public InvalidExpansionContext_Exception(String message, InvalidExpansionContext faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message message
     * @param faultInfo fault
     * @param cause cause
     */
    public InvalidExpansionContext_Exception(String message, InvalidExpansionContext faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hl7.ctsvapi.InvalidExpansionContext
     */
    public InvalidExpansionContext getFaultInfo() {
        return faultInfo;
    }

}
