
package org.hl7.ctsvapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault2", targetNamespace = "urn://hl7.org/CTSVAPI")
public class TimeoutError_Exception extends Exception {

    /**
     * Class UID.
     */
    private static final long serialVersionUID = -7385321541212491533L;
    
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TimeoutError faultInfo;

    /**
     * 
     * @param message message
     * @param faultInfo fault
     */
    public TimeoutError_Exception(String message, TimeoutError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message message
     * @param faultInfo fault
     * @param cause cause
     */
    public TimeoutError_Exception(String message, TimeoutError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hl7.ctsvapi.TimeoutError
     */
    public TimeoutError getFaultInfo() {
        return faultInfo;
    }

}
