
package org.hl7.ctsvapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault9", targetNamespace = "urn://hl7.org/CTSVAPI")
public class UnknownMimeTypeCode_Exception extends Exception {

    /**
     * Class UID.
     */
    private static final long serialVersionUID = 1385458466773527741L;
    
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnknownMimeTypeCode faultInfo;

    /**
     * 
     * @param message message
     * @param faultInfo fault
     */
    public UnknownMimeTypeCode_Exception(String message, UnknownMimeTypeCode faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message message
     * @param faultInfo fault
     * @param cause cause
     */
    public UnknownMimeTypeCode_Exception(String message, UnknownMimeTypeCode faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hl7.ctsvapi.UnknownMimeTypeCode
     */
    public UnknownMimeTypeCode getFaultInfo() {
        return faultInfo;
    }

}
