
package org.hl7.ctsvapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault3", targetNamespace = "urn://hl7.org/CTSVAPI")
public class UnknownRelationshipCode_Exception extends Exception {

    /**
     * Class UID.
     */
    private static final long serialVersionUID = 6246443151644683385L;
    
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnknownRelationshipCode faultInfo;

    /**
     * 
     * @param message message
     * @param faultInfo fault
     */
    public UnknownRelationshipCode_Exception(String message, UnknownRelationshipCode faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message message
     * @param faultInfo fault
     * @param cause cause
     */
    public UnknownRelationshipCode_Exception(String message, UnknownRelationshipCode faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hl7.ctsvapi.UnknownRelationshipCode
     */
    public UnknownRelationshipCode getFaultInfo() {
        return faultInfo;
    }

}
