
package org.hl7;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-07/21/2008 10:18 AM(brewbuilder)-
 * Generated source version: 2.1
 *
 */
@SuppressWarnings("all")
@WebServiceClient(name = "CodeMapping", targetNamespace = "urn://hl7.org/CTSVAPI", wsdlLocation = "file:/home/wellerk/workspace/CTS/WebContent/cts.wsdl")
public class CodeMapping
    extends Service {

    /**
     * URL.
     */
    private static final URL CODEMAPPING_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/home/wellerk/workspace/CTS/WebContent/cts.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CODEMAPPING_WSDL_LOCATION = url;
    }

    /**
     * Constructor.
     * 
     * @param wsdlLocation WSDL
     * @param serviceName service name
     */
    public CodeMapping(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Constructor.
     */
    public CodeMapping() {
        super(CODEMAPPING_WSDL_LOCATION, new QName("urn://hl7.org/CTSVAPI", "CodeMapping"));
    }

    /**
     * Get CodeMappingSoap.
     * 
     * @return
     *     returns CodeMappingSoap
     */
    @WebEndpoint(name = "CodeMappingSoap")
    public CodeMappingSoap getCodeMappingSoap() {
        return (CodeMappingSoap) super.getPort(new QName("urn://hl7.org/CTSVAPI", "CodeMappingSoap"), CodeMappingSoap.class);
    }

    /**
     * Get CodeMappingSoap.
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CodeMappingSoap
     */
    @WebEndpoint(name = "CodeMappingSoap")
    public CodeMappingSoap getCodeMappingSoap(WebServiceFeature... features) {
        return (CodeMappingSoap) super.getPort(new QName("urn://hl7.org/CTSVAPI", "CodeMappingSoap"), CodeMappingSoap.class, features);
    }

}
