
package org.hl7;

import javax.jws.soap.SOAPBinding;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-07/21/2008 10:18 AM(brewbuilder)-
 * Generated source version: 2.1
 *
 */
@SuppressWarnings("all")
@WebService(name = "CodeMappingSoap", targetNamespace = "urn://hl7.org/CTSVAPI")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CodeMappingSoap {


    /**
     * Get CTS version.
     *
     * @return
     *     returns org.hl7.CTSVersionId
     */
    @WebMethod(action = "getCTSVersion")
    @WebResult(name = "getCTSVersionReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "getCTSVersion", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.GetCTSVersion")
    @ResponseWrapper(localName = "getCTSVersionResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.GetCTSVersionResponse")
    public CTSVersionId getCTSVersion();

    /**
     * Get CTS service name.
     *
     * @return
     *     returns org.hl7.ST
     */
    @WebMethod(action = "getServiceName")
    @WebResult(name = "getServiceNameReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "getServiceName", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.GetServiceName")
    @ResponseWrapper(localName = "getServiceNameResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.GetServiceNameResponse")
    public ST getServiceName();

    /**
     * Get CTS service description.
     *
     * @return
     *     returns org.hl7.ST
     */
    @WebMethod(action = "getServiceDescription")
    @WebResult(name = "getServiceDescriptionReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "getServiceDescription", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.GetServiceDescription")
    @ResponseWrapper(localName = "getServiceDescriptionResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.GetServiceDescriptionResponse")
    public ST getServiceDescription();

    /**
     * Get CTS service version.
     *
     * @return
     *     returns org.hl7.ST
     */
    @WebMethod(action = "getServiceVersion")
    @WebResult(name = "getServiceVersionReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "getServiceVersion", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.GetServiceVersion")
    @ResponseWrapper(localName = "getServiceVersionResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.GetServiceVersionResponse")
    public ST getServiceVersion();

    /**
     * Get supported maps.
     *
     * @param parameters parameters
     * @return
     *     returns org.hl7.GetSupportedMapsResponse
     */
    @WebMethod(action = "getSupportedMaps")
    @WebResult(name = "getSupportedMapsResponse", targetNamespace = "urn://hl7.org/CTSVAPI", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetSupportedMapsResponse getSupportedMaps(
        @WebParam(name = "getSupportedMapsVersion", targetNamespace = "urn://hl7.org/CTSVAPI", partName = "parameters")
        GetSupportedMapsVersion parameters);

    /**
     * Map code.
     *
     * @param toCodeSystemId to coding system
     * @param fromConceptId from concept id
     * @param mapName map name
     * @return
     *     returns org.hl7.MappedConceptCode
     */
    @WebMethod(action = "mapCode")
    @WebResult(name = "mapCodeReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "mapCode", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.MapCode")
    @ResponseWrapper(localName = "mapCodeResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.MapCodeResponse")
    public MappedConceptCode mapCode(
        @WebParam(name = "fromConceptId", targetNamespace = "urn://hl7.org/CTSVAPI")
        ConceptId fromConceptId,
        @WebParam(name = "toCodeSystemId", targetNamespace = "urn://hl7.org/CTSVAPI")
        String toCodeSystemId,
        @WebParam(name = "mapName", targetNamespace = "urn://hl7.org/CTSVAPI")
        String mapName);

}
