
package org.hl7.ctsvapi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BrowserOperations", targetNamespace = "urn://hl7.org/CTSVAPI")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BrowserOperations {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws UnexpectedError_Exception exception
     */
    @WebMethod
    @WebResult(name = "getSupportedMatchAlgorithmsReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "getSupportedMatchAlgorithms", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetSupportedMatchAlgorithms")
    @ResponseWrapper(localName = "getSupportedMatchAlgorithmsResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetSupportedMatchAlgorithmsResponse")
    public List<String> getSupportedMatchAlgorithms()
        throws UnexpectedError_Exception;

    /**
     * 
     * @param contextToExpand context
     * @return
     *     returns java.util.List<org.hl7.ctsvapi.RelatedCode>
     * @throws UnexpectedError_Exception exception
     * @throws TimeoutError_Exception exception
     * @throws InvalidExpansionContext_Exception exception
     */
    @WebMethod
    @WebResult(name = "expandCodeExpansionContextReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "expandCodeExpansionContext", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.ExpandCodeExpansionContext")
    @ResponseWrapper(localName = "expandCodeExpansionContextResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.ExpandCodeExpansionContextResponse")
    public List<RelatedCode> expandCodeExpansionContext(
        @WebParam(name = "contextToExpand", targetNamespace = "urn://hl7.org/CTSVAPI")
        byte[] contextToExpand)
        throws InvalidExpansionContext_Exception, TimeoutError_Exception, UnexpectedError_Exception;

    /**
     * 
     * @param relationshipCode relationship
     * @param designationLanguageCode language
     * @param sizeLimit limit
     * @param expandConceptId concept
     * @param sourceToTarget source
     * @param timeout timeout
     * @param directRelationsOnly direct
     * @return
     *     returns java.util.List<org.hl7.ctsvapi.RelatedCode>
     * @throws UnknownConceptCode_Exception exception
     * @throws UnknownLanguageCode_Exception exception
     * @throws UnknownCodeSystem_Exception exception
     * @throws UnexpectedError_Exception exception
     * @throws TimeoutError_Exception exception
     * @throws UnknownRelationshipCode_Exception exception
     */
    @WebMethod
    @WebResult(name = "lookupCodeExpansionReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "lookupCodeExpansion", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupCodeExpansion")
    @ResponseWrapper(localName = "lookupCodeExpansionResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupCodeExpansionResponse")
    public List<RelatedCode> lookupCodeExpansion(
        @WebParam(name = "expandConcept_id", targetNamespace = "urn://hl7.org/CTSVAPI")
        ConceptId expandConceptId,
        @WebParam(name = "relationship_code", targetNamespace = "urn://hl7.org/CTSVAPI")
        String relationshipCode,
        @WebParam(name = "sourceToTarget", targetNamespace = "urn://hl7.org/CTSVAPI")
        boolean sourceToTarget,
        @WebParam(name = "directRelationsOnly", targetNamespace = "urn://hl7.org/CTSVAPI")
        boolean directRelationsOnly,
        @WebParam(name = "designationLanguage_code", targetNamespace = "urn://hl7.org/CTSVAPI")
        String designationLanguageCode,
        @WebParam(name = "timeout", targetNamespace = "urn://hl7.org/CTSVAPI")
        int timeout,
        @WebParam(name = "sizeLimit", targetNamespace = "urn://hl7.org/CTSVAPI")
        int sizeLimit)
        throws TimeoutError_Exception, UnexpectedError_Exception, UnknownCodeSystem_Exception, UnknownConceptCode_Exception, UnknownLanguageCode_Exception, UnknownRelationshipCode_Exception;

    /**
     * 
     * @param sizeLimit limit
     * @param timeout timeout
     * @return
     *     returns java.util.List<org.hl7.ctsvapi.CodeSystemIdAndVersions>
     * @throws UnexpectedError_Exception exception
     * @throws TimeoutError_Exception exception
     */
    @WebMethod
    @WebResult(name = "getSupportedCodeSystemsReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "getSupportedCodeSystems", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetSupportedCodeSystems")
    @ResponseWrapper(localName = "getSupportedCodeSystemsResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetSupportedCodeSystemsResponse")
    public List<CodeSystemIdAndVersions> getSupportedCodeSystems(
        @WebParam(name = "timeout", targetNamespace = "urn://hl7.org/CTSVAPI")
        int timeout,
        @WebParam(name = "sizeLimit", targetNamespace = "urn://hl7.org/CTSVAPI")
        int sizeLimit)
        throws TimeoutError_Exception, UnexpectedError_Exception;

    /**
     * 
     * @param conceptId concept
     * @return
     *     returns org.hl7.ctsvapi.CompleteCodedConceptDescription
     * @throws UnknownConceptCode_Exception exception
     * @throws UnknownCodeSystem_Exception exception
     * @throws UnexpectedError_Exception exception
     */
    @WebMethod
    @WebResult(name = "lookupCompleteCodedConceptReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "lookupCompleteCodedConcept", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupCompleteCodedConcept")
    @ResponseWrapper(localName = "lookupCompleteCodedConceptResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupCompleteCodedConceptResponse")
    public CompleteCodedConceptDescription lookupCompleteCodedConcept(
        @WebParam(name = "concept_id", targetNamespace = "urn://hl7.org/CTSVAPI")
        ConceptId conceptId)
        throws UnexpectedError_Exception, UnknownCodeSystem_Exception, UnknownConceptCode_Exception;

    /**
     * 
     * @param languageCode language
     * @param activeConceptsOnly active
     * @param matchAlgorithmCode algorithm
     * @param sizeLimit limit
     * @param matchText match
     * @param timeout timeout
     * @param codeSystemId code system
     * @return
     *     returns java.util.List<org.hl7.ctsvapi.ConceptId>
     * @throws UnknownLanguageCode_Exception exception
     * @throws BadlyFormedMatchText_Exception exception
     * @throws UnexpectedError_Exception exception
     * @throws TimeoutError_Exception exception
     * @throws UnknownCodeSystem_Exception exception
     * @throws UnknownMatchAlgorithm_Exception exception
     */
    @WebMethod
    @WebResult(name = "lookupConceptCodesByDesignationReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "lookupConceptCodesByDesignation", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupConceptCodesByDesignation")
    @ResponseWrapper(localName = "lookupConceptCodesByDesignationResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupConceptCodesByDesignationResponse")
    public List<ConceptId> lookupConceptCodesByDesignation(
        @WebParam(name = "codeSystem_id", targetNamespace = "urn://hl7.org/CTSVAPI")
        String codeSystemId,
        @WebParam(name = "matchText", targetNamespace = "urn://hl7.org/CTSVAPI")
        String matchText,
        @WebParam(name = "matchAlgorithm_code", targetNamespace = "urn://hl7.org/CTSVAPI")
        String matchAlgorithmCode,
        @WebParam(name = "language_code", targetNamespace = "urn://hl7.org/CTSVAPI")
        String languageCode,
        @WebParam(name = "activeConceptsOnly", targetNamespace = "urn://hl7.org/CTSVAPI")
        boolean activeConceptsOnly,
        @WebParam(name = "timeout", targetNamespace = "urn://hl7.org/CTSVAPI")
        int timeout,
        @WebParam(name = "sizeLimit", targetNamespace = "urn://hl7.org/CTSVAPI")
        int sizeLimit)
        throws BadlyFormedMatchText_Exception, TimeoutError_Exception, UnexpectedError_Exception, UnknownCodeSystem_Exception, UnknownLanguageCode_Exception, UnknownMatchAlgorithm_Exception;

    /**
     * 
     * @param languageCode language
     * @param activeConceptsOnly active
     * @param matchAlgorithmCode algorithm
     * @param sizeLimit limit
     * @param properties properties
     * @param matchText match
     * @param mimeTypes types
     * @param timeout timeout
     * @param codeSystemId code system
     * @return
     *     returns java.util.List<org.hl7.ctsvapi.ConceptId>
     * @throws UnknownLanguageCode_Exception exception
     * @throws UnexpectedError_Exception exception
     * @throws UnknownCodeSystem_Exception exception
     * @throws BadlyFormedMatchText_Exception exception
     * @throws TimeoutError_Exception exception
     * @throws UnknownPropertyCode_Exception exception
     * @throws UnknownMimeTypeCode_Exception exception
     * @throws UnknownMatchAlgorithm_Exception exception
     */
    @WebMethod
    @WebResult(name = "lookupConceptCodesByPropertyReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "lookupConceptCodesByProperty", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupConceptCodesByProperty")
    @ResponseWrapper(localName = "lookupConceptCodesByPropertyResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupConceptCodesByPropertyResponse")
    public List<ConceptId> lookupConceptCodesByProperty(
        @WebParam(name = "codeSystem_id", targetNamespace = "urn://hl7.org/CTSVAPI")
        String codeSystemId,
        @WebParam(name = "matchText", targetNamespace = "urn://hl7.org/CTSVAPI")
        String matchText,
        @WebParam(name = "matchAlgorithm_code", targetNamespace = "urn://hl7.org/CTSVAPI")
        String matchAlgorithmCode,
        @WebParam(name = "language_code", targetNamespace = "urn://hl7.org/CTSVAPI")
        String languageCode,
        @WebParam(name = "activeConceptsOnly", targetNamespace = "urn://hl7.org/CTSVAPI")
        boolean activeConceptsOnly,
        @WebParam(name = "properties", targetNamespace = "urn://hl7.org/CTSVAPI")
        List<String> properties,
        @WebParam(name = "mimeTypes", targetNamespace = "urn://hl7.org/CTSVAPI")
        List<String> mimeTypes,
        @WebParam(name = "timeout", targetNamespace = "urn://hl7.org/CTSVAPI")
        int timeout,
        @WebParam(name = "sizeLimit", targetNamespace = "urn://hl7.org/CTSVAPI")
        int sizeLimit)
        throws BadlyFormedMatchText_Exception, TimeoutError_Exception, UnexpectedError_Exception, UnknownCodeSystem_Exception, UnknownLanguageCode_Exception, UnknownMatchAlgorithm_Exception, UnknownMimeTypeCode_Exception, UnknownPropertyCode_Exception;

    /**
     * 
     * @param languageCode language
     * @param matchAlgorithmCode algorithm
     * @param matchText match
     * @param conceptCode code
     * @return
     *     returns java.util.List<org.hl7.ctsvapi.ConceptDesignation>
     * @throws UnknownConceptCode_Exception exception
     * @throws UnknownLanguageCode_Exception exception
     * @throws UnexpectedError_Exception exception
     * @throws BadlyFormedMatchText_Exception exception
     * @throws UnknownCodeSystem_Exception exception
     * @throws UnknownMatchAlgorithm_Exception exception
     */
    @WebMethod
    @WebResult(name = "lookupDesignationsReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "lookupDesignations", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupDesignations")
    @ResponseWrapper(localName = "lookupDesignationsResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupDesignationsResponse")
    public List<ConceptDesignation> lookupDesignations(
        @WebParam(name = "conceptCode", targetNamespace = "urn://hl7.org/CTSVAPI")
        ConceptId conceptCode,
        @WebParam(name = "matchText", targetNamespace = "urn://hl7.org/CTSVAPI")
        String matchText,
        @WebParam(name = "matchAlgorithm_code", targetNamespace = "urn://hl7.org/CTSVAPI")
        String matchAlgorithmCode,
        @WebParam(name = "languageCode", targetNamespace = "urn://hl7.org/CTSVAPI")
        String languageCode)
        throws BadlyFormedMatchText_Exception, UnexpectedError_Exception, UnknownCodeSystem_Exception, UnknownConceptCode_Exception, UnknownLanguageCode_Exception, UnknownMatchAlgorithm_Exception;

    /**
     * 
     * @param languageCode language
     * @param conceptId concept
     * @param matchAlgorithmCode algorithm
     * @param matchText match
     * @param properties properties
     * @param mimeTypes types
     * @return
     *     returns java.util.List<org.hl7.ctsvapi.ConceptProperty>
     * @throws UnknownConceptCode_Exception exception
     * @throws UnknownLanguageCode_Exception exception
     * @throws UnknownCodeSystem_Exception exception
     * @throws UnexpectedError_Exception exception
     * @throws BadlyFormedMatchText_Exception exception
     * @throws UnknownPropertyCode_Exception exception
     * @throws UnknownMimeTypeCode_Exception exception
     * @throws UnknownMatchAlgorithm_Exception exception
     */
    @WebMethod
    @WebResult(name = "lookupPropertiesReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "lookupProperties", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupProperties")
    @ResponseWrapper(localName = "lookupPropertiesResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.LookupPropertiesResponse")
    public List<ConceptProperty> lookupProperties(
        @WebParam(name = "concept_id", targetNamespace = "urn://hl7.org/CTSVAPI")
        ConceptId conceptId,
        @WebParam(name = "properties", targetNamespace = "urn://hl7.org/CTSVAPI")
        List<String> properties,
        @WebParam(name = "matchText", targetNamespace = "urn://hl7.org/CTSVAPI")
        String matchText,
        @WebParam(name = "matchAlgorithm_code", targetNamespace = "urn://hl7.org/CTSVAPI")
        String matchAlgorithmCode,
        @WebParam(name = "language_code", targetNamespace = "urn://hl7.org/CTSVAPI")
        String languageCode,
        @WebParam(name = "mimeTypes", targetNamespace = "urn://hl7.org/CTSVAPI")
        List<String> mimeTypes)
        throws BadlyFormedMatchText_Exception, UnexpectedError_Exception, UnknownCodeSystem_Exception, UnknownConceptCode_Exception, UnknownLanguageCode_Exception, UnknownMatchAlgorithm_Exception, UnknownMimeTypeCode_Exception, UnknownPropertyCode_Exception;

    /**
     * 
     * @return
     *     returns org.hl7.ctsvapi.CTSVersionId
     * @throws UnexpectedError_Exception exception
     */
    @WebMethod
    @WebResult(name = "getCTSVersionReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "getCTSVersion", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetCTSVersion")
    @ResponseWrapper(localName = "getCTSVersionResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetCTSVersionResponse")
    public CTSVersionId getCTSVersion()
        throws UnexpectedError_Exception;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws UnexpectedError_Exception exception
     */
    @WebMethod
    @WebResult(name = "getServiceDescriptionReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "getServiceDescription", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetServiceDescription")
    @ResponseWrapper(localName = "getServiceDescriptionResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetServiceDescriptionResponse")
    public String getServiceDescription()
        throws UnexpectedError_Exception;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws UnexpectedError_Exception exception
     */
    @WebMethod
    @WebResult(name = "getServiceNameReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "getServiceName", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetServiceName")
    @ResponseWrapper(localName = "getServiceNameResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetServiceNameResponse")
    public String getServiceName()
        throws UnexpectedError_Exception;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws UnexpectedError_Exception exception
     */
    @WebMethod
    @WebResult(name = "getServiceVersionReturn", targetNamespace = "urn://hl7.org/CTSVAPI")
    @RequestWrapper(localName = "getServiceVersion", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetServiceVersion")
    @ResponseWrapper(localName = "getServiceVersionResponse", targetNamespace = "urn://hl7.org/CTSVAPI", className = "org.hl7.ctsvapi.GetServiceVersionResponse")
    public String getServiceVersion()
        throws UnexpectedError_Exception;

}
