
package org.hl7.ctsvapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault", targetNamespace = "urn://hl7.org/CTSVAPI")
public class UnexpectedError_Exception extends Exception {

    /**
     * Class UID.
     */
    private static final long serialVersionUID = -5257945064018081025L;
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnexpectedError faultInfo;

    /**
     * 
     * @param message message
     * @param faultInfo fault
     */
    public UnexpectedError_Exception(String message, UnexpectedError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message message
     * @param faultInfo fault
     * @param cause cause
     */
    public UnexpectedError_Exception(String message, UnexpectedError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hl7.ctsvapi.UnexpectedError
     */
    public UnexpectedError getFaultInfo() {
        return faultInfo;
    }

}
