
package org.hl7.ctsvapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault5", targetNamespace = "urn://hl7.org/CTSVAPI")
public class UnknownCodeSystem_Exception extends Exception {

    /**
     * Class UID.
     */
    private static final long serialVersionUID = -4397774308314033398L;
    
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnknownCodeSystem faultInfo;

    /**
     * 
     * @param message message
     * @param faultInfo fault
     */
    public UnknownCodeSystem_Exception(String message, UnknownCodeSystem faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message message
     * @param faultInfo fault
     * @param cause cause
     */
    public UnknownCodeSystem_Exception(String message, UnknownCodeSystem faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hl7.ctsvapi.UnknownCodeSystem
     */
    public UnknownCodeSystem getFaultInfo() {
        return faultInfo;
    }

}
