
package org.hl7.ctsvapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault6", targetNamespace = "urn://hl7.org/CTSVAPI")
public class UnknownLanguageCode_Exception extends Exception {

    /**
     * Class UID.
     */
    private static final long serialVersionUID = -2578739802076461809L;
    
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnknownLanguageCode faultInfo;

    /**
     * 
     * @param message message
     * @param faultInfo fault
     */
    public UnknownLanguageCode_Exception(String message, UnknownLanguageCode faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message message
     * @param faultInfo fault
     * @param cause cause
     */
    public UnknownLanguageCode_Exception(String message, UnknownLanguageCode faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hl7.ctsvapi.UnknownLanguageCode
     */
    public UnknownLanguageCode getFaultInfo() {
        return faultInfo;
    }

}
