
package org.hl7.ctsvapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault4", targetNamespace = "urn://hl7.org/CTSVAPI")
public class UnknownConceptCode_Exception extends Exception {

    /**
     * Class UID.
     */
    private static final long serialVersionUID = 4449644516429551482L;
    
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnknownConceptCode faultInfo;

    /**
     * 
     * @param message message
     * @param faultInfo fault
     */
    public UnknownConceptCode_Exception(String message, UnknownConceptCode faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message message
     * @param faultInfo fault
     * @param cause cause
     */
    public UnknownConceptCode_Exception(String message, UnknownConceptCode faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hl7.ctsvapi.UnknownConceptCode
     */
    public UnknownConceptCode getFaultInfo() {
        return faultInfo;
    }

}
