
package org.hl7.ctsvapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault8", targetNamespace = "urn://hl7.org/CTSVAPI")
public class UnknownMatchAlgorithm_Exception extends Exception {

    /**
     * Class UID.
     */
    private static final long serialVersionUID = 547514442663820390L;
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnknownMatchAlgorithm faultInfo;

    /**
     * 
     * @param message message
     * @param faultInfo fault
     */
    public UnknownMatchAlgorithm_Exception(String message, UnknownMatchAlgorithm faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message message
     * @param faultInfo fault
     * @param cause cause
     */
    public UnknownMatchAlgorithm_Exception(String message, UnknownMatchAlgorithm faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hl7.ctsvapi.UnknownMatchAlgorithm
     */
    public UnknownMatchAlgorithm getFaultInfo() {
        return faultInfo;
    }

}
